### ISSUE TITLE
axlsx 2.0.1 depends on rubyzip ~> 1.0.0? 

### ISSUE THREAD

**Issue by mllocs** [randym/axlsx#446]
I don't understand why I get this error if the dependency with rubyzip was updated 2 years ago https://github.com/randym/axlsx/commit/9e07402a26f776b6dcdc264a202d804c5d24e8b3. 

![](https://www.dropbox.com/s/rrjmn20hykhqar2/Screenshot%202016-02-04%2011.28.58.png?dl=1)

**Comment by guzart** [comment]
Because the version `2.0.1` [was released](https://github.com/randym/axlsx/commit/46a17e4b3fe0531ac6b2e48f818a982a86f538e4) Sep 12, 2013.

There's another "alpha/beta" release "2.1.0.pre", you could set that as the gem version in your Gemfile, or a specific commit after [c649ee7d5ac699d0fc5a36550f502216f9b7318f](https://github.com/randym/axlsx/commit/c649ee7d5ac699d0fc5a36550f502216f9b7318f)

**Comment by mllocs** [comment]
Ops sorry, I guess I got confused with 2.0.1 and 2.1.0. 
Any plans to release the 2.1.0 version? I see that it's been published as `pre` since March 2015.
Thanks!
