### ISSUE TITLE
Ternary operator does not work as expected 

### ISSUE THREAD

**Issue by yidingalan** [randym/axlsx#534]
the `add_sheet` throws an syntax error when I put it under ternary operator 
```
results_forward == nil ? sheet.add_row [report.study_observation_sets[0][:address], report.study_observation_sets[1][:address], t("not_applicable")] : sheet.add_row [report.study_observation_sets[0][:address], report.study_observation_sets[1][:address], results_forward[:pt_index_am], results_forward[:pt_index_pm], results_forward[:tt_index_am], results_forward[:tt_index_pm], results_forward[:bt_index_am], results_forward[:bt_index_pm]]
```
error message
```
syntax error, unexpected [, expecting ':'
rward == nil ? sheet.add_row [report.study_observation_sets[
```

**Comment by p-salido** [comment]
You should put some parentheses in there, Ruby must be sensitive to whitespace in a construct like `f ? a [b] : c [d]`. It will probably work with either `f ? a[b] : c[d]` or `f ? a([b]) : c([d])` but really, you should not be using ternaries in the first place. The line you posted is just about unreadable due to its length.

**Comment by yidingalan** [comment]
@p-salido I don't think that's the issue here
